### PR TITLE
Support OpenShift 4.9

### PR DESCRIPTION
**Pull request by liveaverage**
- Update iPXE script for new rootfs file
- Update ignition to latest versions
- Update missing zone_id ref for cloudflare

### CODE REVIEW

**Comment by liveaverage** [comment]
@displague just let me know if I need to provide any extra detail around changes... figured I'd update while native IPI support progresses :)

**Comment by displague** [comment]
I've made a change to keep Cloudflare as an optional DNS provider. The latest CloudFlare provider added api_key validation which was blocking other providers from being used.

**Comment by liveaverage** [comment]
Good catch on `api_key` validation. WRT to pull secret, yes, the bearer token may need to be refreshed, though it's not a frequent requirement.

**Comment by displague** [comment]
I had some trouble accessing these nodes after the coreos reboots.

**Comment by liveaverage** [comment]
Are you referring to accessing nodes via SSH or OOB console (SOS)? The latter is a problem that existed in the previous automation, too. Kernel args don't persist, so dropping into SOS requires intercepting boot and adding the appropriate console param back in.

**Comment by displague** [comment]
@liveaverage would this help? https://github.com/openshift/machine-config-operator/blob/8fa45661c50047de097db3ed7592e48910bfe401/docs/MachineConfiguration.md#kernelarguments

**Comment by liveaverage** [comment]
Let me retest with day 1 kernel arg updates documented here: https://github.com/openshift/installer/blob/master/docs/user/customization.md#nodes-with-custom-kernel-arguments -- technically we're supposed to make the initial kargs "sticky", but that's still not happening so I'll need to tweak MachineConfigs post-config generation and pre-installl. It can be modified as a day 2 activity as well, but easier for troubleshooting to do this day 1!

**Pull request merged**
